version: "3.3"
services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/Project
      SPRING_DATASOURCE_USERNAME: newuser
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - app_network

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8080
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Project
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local


